
####################################################################################
# Generated by Vivado 2024.2 built on 'Fri Nov 08 22:34:34 MST 2024' by 'xbuild'
# Command Used: write_xdc effective_constraints.xdc
####################################################################################


####################################################################################
# Constraints from file : 'constraints.xdc'
####################################################################################

# OOC contract only: synchronous AXI/AXI-Lite peers on the same 100MHz clock.
# 2ns external max delay, 0ns external min delay; no board pin assumptions.
# 2.7ns setup budget preserves the HLS scheduling margin. Hold uses the
# physical clock skew/jitter model; no artificial 2.7ns hold uncertainty.
create_clock -period 10.000 -name ap_clk [get_ports ap_clk]
set_clock_uncertainty -setup 2.700 [get_clocks ap_clk]
set _xlnx_shared_i0 [get_ports -filter {DIRECTION == IN && NAME != ap_clk}]
set_input_delay -clock ap_clk -max 2.000 $_xlnx_shared_i0
set_input_delay -clock ap_clk -min 0.000 $_xlnx_shared_i0
set _xlnx_shared_i1 [get_ports -filter {DIRECTION == OUT}]
set_output_delay -clock ap_clk -max 2.000 $_xlnx_shared_i1
set_output_delay -clock ap_clk -min 0.000 $_xlnx_shared_i1
# Reset is included in the synchronous boundary contract; no false paths.


# User Generated miscellaneous constraints 

set_property HD.CLK_SRC BUFGCE_X0Y48 [get_ports ap_clk]

# User Generated physical constraints 

set_property LOC BUFGCE_X0Y50 [get_cells grp_run_fu_161/grp_runController_fu_106/grp_runQueryTile_fu_142/runQueryBlock_0_U0/grp_runAccumulatorColumns_fu_512_i_2_bufg_place]
set_property LOC BUFGCE_X0Y80 [get_cells grp_run_fu_161/grp_runController_fu_106/grp_runQueryTile_fu_142/runQueryBlock_1_U0/grp_runAccumulatorColumns_fu_551_i_2_bufg_place]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
